apiVersion : apps/v1
kind: Deployment
metadata:
  name: "wubot2-ede5"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "wubot2-ede5"
  template:
    metadata:
      labels:
        app: "wubot2-ede5"
    spec:
      containers:
        - name: "wubot2-ede5"
          image: "callm2.azurecr.io/wubot2"
          ports:
          - containerPort: 80